<li> <a href="[field:arcurl/]" target="_blank">
      <div class="opt_left"> <img src="[field:litpic/]" border="0" /> <em class="opt_mask_left"></em> <em class="opt_mask_right"></em>
        <div class="border_white"></div>
      </div>
      <div class="opt_right">
        <div class="opt_title"> [field:title/] </div>
        <div class="opt_price"> <span>全包价</span> <sub>￥</sub> [field:shorttitle/] <sup>2</sup> </div>
        <div class="opt_describe"> [field:description function='cn_substr(@me,120)'/] </div>
        <span class="plan_details"><i></i>套餐详情</span> </div>
      </a> </li>