<?php
$z[0]=Array("type","\r\r\n          <dt> <a id=\"before\" href=\" [field:typeurl/]\"> <s></s>[field:typename/] </a> </dt>\r\r\n          ",126,267);
$z[0][4]['typeid']="6";
$z[1]=Array("channel","\r\r\n          <dd><a id=\"sheji\" href='[field:typeurl/]'>[field:typename/]</a></dd>\r\r\n          ",293,441);
$z[1][4]['type']="son";
$z[1][4]['typeid']="6";
$z[2]=Array("type","\r\r\n          <dt><a id=\"ing\" href='[field:typeurl/]'><s></s>[field:typename/]</a></dt>\r\r\n          ",580,713);
$z[2][4]['typeid']="7";
$z[3]=Array("channel","\r\r\n          <dd><a id=\"shuidian\" href=\"[field:typeurl/]\">[field:typename/]</a></dd>\r\r\n          ",739,890);
$z[3][4]['type']="son";
$z[3][4]['typeid']="7";
$z[4]=Array("type","\r\r\n          <dt><a id=\"after\" href=\"[field:typeurl/]\"><s></s>[field:typename/]</a></dt>\r\r\n          ",1031,1166);
$z[4][4]['typeid']="8";
$z[5]=Array("channel","\r\r\n          <dd><a id=\"ruzhu\" href=\"[field:typeurl/]\">[field:typename/]</a></dd>\r\r\n          ",1192,1340);
$z[5][4]['type']="son";
$z[5][4]['typeid']="8";

?>