<?php
$z[0]=Array("global","",215,241);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",286,316);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",354,381);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("field","",477,535);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("channel","\r\n        <li><a href='[field:typeurl/]' target=\"_blank\">[field:typename/]</a></li>\r\n        ",1258,1400);
$z[4][4]['type']="top";
$z[4][4]['row']="4";
$z[5]=Array("myad","",3632,3653);
$z[5][4]['name']="1";
$z[6]=Array("type","\r\n        <li>[field:typename/]</li>\r\n        ",11968,12049);
$z[6][4]['typeid']="46";
$z[7]=Array("arclist","\r\n              <li>\r\n            <ul>\r\n                  <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                  <li></li>\r\n                  <li></li>\r\n                  <li>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</li>\r\n                </ul>\r\n          </li>\r\n              ",12216,12599);
$z[7][4]['typeid']="46";
$z[7][4]['row']="25";
$z[7][4]['titlelen']="50";
$z[7][4]['orderby']="pubdate";
$z[8]=Array("myad","",12636,12657);
$z[8][4]['name']="2";
$z[9]=Array("arclist","\r\n    <li> <a href=\"[field:arcurl/]\" target=\"_blank\">\r\n      <div class=\"opt_left\"> <img src=\"[field:litpic/]\" border=\"0\" /> <em class=\"opt_mask_left\"></em> <em class=\"opt_mask_right\"></em>\r\n        <div class=\"border_white\"></div>\r\n      </div>\r\n      <div class=\"opt_right\">\r\n        <div class=\"opt_title\"> [field:title/] </div>\r\n        <div class=\"opt_price\"> <span>全包价</span> <sub>￥</sub> [field:shorttitle/] <sup>2</sup> </div>\r\n        <div class=\"opt_describe\"> [field:description function='cn_substr(@me,120)'/] </div>\r\n        <span class=\"plan_details\"><i></i>套餐详情</span> </div>\r\n      </a> </li>\r\n    ",12973,13674);
$z[9][4]['row']="13";
$z[9][4]['titlelen']="32";
$z[9][4]['noflag']="h";
$z[9][4]['typeid']="46";
$z[10]=Array("myad","",13906,13927);
$z[10][4]['name']="3";
$z[11]=Array("include","",13950,13983);
$z[11][4]['filename']="f1.htm";

?>