<?php
$z[0]=Array("type","\r\n      <dd><a href=\"[field:typeurl/]\"><s class=\"jy_cy\"></s>[field:typename/]</a></dd>\r\n      ",143,272);
$z[0][4]['typeid']="30";
$z[1]=Array("type","\r\n      <dd><a href=\"[field:typeurl/]\"><s class=\"jy_cz\"></s>[field:typename/]</a></dd>\r\n      ",288,417);
$z[1][4]['typeid']="31";
$z[2]=Array("type","\r\n      <dd><a href=\"[field:typeurl/]\"><s class=\"jy_db\"></s>[field:typename/]</a></dd>\r\n      ",433,562);
$z[2][4]['typeid']="32";
$z[3]=Array("type","\r\n      <dd><a href=\"[field:typeurl/]\"><s class=\"jy_cg\"></s>[field:typename/]</a></dd>\r\n      ",578,707);
$z[3][4]['typeid']="33";
$z[4]=Array("type","\r\n      <dd><a href=\"[field:typeurl/]\"><s class=\"jy_wy\"></s>[field:typename/]</a></dd>\r\n      ",723,852);
$z[4][4]['typeid']="34";
$z[5]=Array("type","\r\n      <dd><a href=\"[field:typeurl/]\"><s class=\"jy_yq\"></s>[field:typename/]</a></dd>\r\n      ",868,997);
$z[5][4]['typeid']="35";
$z[6]=Array("type","\r\n      <dd><a href=\"[field:typeurl/]\"><s class=\"jy_jq\"></s>[field:typename/]</a></dd>\r\n      ",1013,1142);
$z[6][4]['typeid']="36";
$z[7]=Array("type","\r\n      <dd><a href=\"[field:typeurl/]\"><s class=\"jy_sn\"></s>[field:typename/]</a></dd>\r\n      ",1158,1287);
$z[7][4]['typeid']="37";
$z[8]=Array("arclist","\r\n      <li class=\"page_item page-item-385\"><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n      ",1409,1559);
$z[8][4]['row']="6";
$z[8][4]['typeid']="10";

?>